### PR TITLE
Supporting dynamic ports

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by ngauthier** [comment]
LGTM :clap:

**Comment by sr** [comment]
Can you clarify what's this for? what's a dynamic port?

**Comment by ngauthier** [comment]
A port that doesn't have an external side. So we support:

123:123

But this supports:

123

That will get dynamically mapped to an external port so as to avoid conflicts.

**Comment by bfosberry** [comment]
thanks @ngauthier  :P

**Comment by ngauthier** [comment]
See also https://docs.docker.com/compose/yml/#ports

**Comment by sr** [comment]
Gotcha.

**Comment by sr** [comment]
Aaah. This? https://github.com/codeship/codeship-tool/issues/17

**Comment by bfosberry** [comment]
Yep!

**Pull request merged**
